### PR TITLE
bower support

### PR DESCRIPTION
**Pull request by mythteria**
added bower.json file
...and then we can register ko.plus for bower

### CODE REVIEW

**Comment by stevegreatrex** [comment]
Nice - I've been meaning to do this for a while!

**Comment by mythteria** [comment]
Steve, could you change ko dependency in bower.json to knockoutjs? Or i can make another PR...

**Comment by stevegreatrex** [comment]
The knockout bower package is just `knockout`...

(See https://github.com/knockout/knockout/blob/master/bower.json)

**Comment by mythteria** [comment]
You're right (and i thought the same), but... 
`bower search knockout`
shows that we need knockoutjs. i think.

**Comment by stevegreatrex** [comment]
Good point; updated!

**Pull request merged**
