### PR TITLE
#13 Add reset method

### PR DESCRIPTION
**Pull request by HakanL**

### CODE REVIEW

**Comment by stevegreatrex** [comment]
Hi Hakan, thanks for this contribution.  If you add some unit tests then I can re-run the build and sort out the Travis CI issues.

Steve

**Comment by HakanL** [comment]
Fixed the tabs and added a unit test for the reset function

**Comment by stevegreatrex** [comment]
Build is still failing...are you running the grunt jshint task locally?

**Comment by HakanL** [comment]
Sorry, it seems that my VS decided to put spaces there instead of tabs. I've manually changed it now (in the unit tests this time). Please retry. I don't have grunt on my machine so I haven't tried that locally :(

**Pull request merged**
