### PR TITLE
Added locale option for sortable extender. 

### PR DESCRIPTION
**Pull request by SondreHusevold**
### Locale option
The sortable extender will sort purely on character codes which causes characters like "Æ, Ø, Å" or similar language specific characters to be sorted in the wrong order. 

The extender now takes an optional "locale" option that is a string with a BCP 47 language tag, like 'no', 'sv', 'en' that will use localeCompare when comparing the strings.

If the locale option is not specified, it will sort using character codes as normal.

Example: 
`var myArray = ko.observableArray(['Ø', 'A', 't']).extend({ sortable: { locale: 'no' } })`

### Unit Tests
Two unit tests have been added for the locale option. It will attempt to sort the Norwegian letters "æ", "ø" and "å" correctly by using the 'no' locale. 

### Performance
Only if the locale option is specified it will use the [localeCompare](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare) method. The reason for keeping the old implementation is simply that localeCompare is far slower than comparing character codes.

Another solution would be using [Intl.Collator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Collator) instead of localeCompare. Performance in this case would be improved, especially for larger arrays. The downside is PhantomJS does not have support for Intl.Collator and the [Intl polyfill](https://github.com/andyearnshaw/Intl.js) does not want to/has not yet implemented the Intl.Collator. That means there will be no unit tests for the locale option if we opt to use Intl.Collator instead of localeCompare.

### Conclusion
I'm not sure whether the Intl.Collator or the localeCompare solution is the best way. The Intl.Collator will give large performance boosts when using the locale option, on the other hand the lack of unit tests for the option is scary. 

Thus the initial pull request is only for the localeCompare solution. If the Intl.Collator solution is deemed better, I can change the implementation to use the Intl.Collator instead.

### CODE REVIEW

**Comment by stevegreatrex** [comment]
Nice!  All looks good to me - just need to persuade jshint to allow the characters in the tests and then we can merge

**Comment by SondreHusevold** [comment]
I've taken a look at the issue. Seems like the encoding on the ko.sortable.tests.js file is ANSI instead of UTF-8 which causes the characters to appear weird and jshint throwing errors.

Changing the encoding to UTF-8 breaks the new locale unit tests, which probably means they never worked in the first place. Sorry about that.

The reason for them breaking is due to grunt-contrib-qunit's PhantomJS version (1.9.8) having a bug in its localeCompare implementation. 

Apparently [it doesn't return](https://github.com/ariya/phantomjs/issues/11063) [the correct results](https://github.com/ariya/phantomjs/issues/14496) which I believe I can personally confirm below: 

image

I can confirm PhantomJS 2.0.0+ does indeed return the correct value. However that would imply upgrading npm packages and all the baggage that brings. 

I'm not sure how the proceed here. The unit tests simply passed due to the ANSI unknown character being identical, now they won't pass whatsoever due to a bug in an older PhantomJS version. 

Upgrading grunt-contrib-qunit to minimum version ~1.0.0 (where PhantomJS 2.0 was introduced) instead of ~0.2.2 solves the PhanthomJS localeCompare issue, but breaks the entire unit test system currently in place.

Any ideas?

**Comment by stevegreatrex** [comment]
It sounds like the best bet is to upgrade the old dependency and get the tests working there. 

What's your feeling on effort to solve the problems you've seen?

**Comment by SondreHusevold** [comment]
Been working on this for the past few hours, haven't reached a complete solution yet, but should hopefully be around the corner. 

So far the easiest way seems to be to upgrade grunt-contrib-qunit. 

Once I got something concrete I'll do some cleanups and do an update on the PR.

**Comment by SondreHusevold** [comment]
Thank you for your patience. 

### Changes:
The sorter now uses an Intl.Collator object if the locale option is specified. This allows for far better performance than with localeCompare. 

I also added one more unit test for testing descending sorting with the locale option enabled. 

Feel free to look it over.

**Review by stevegreatrex — APPROVED** [review]
LGTM

**Comment by SimmeNilsson** [comment]
Will the npm package get updated with this? :)

**Pull request merged**
